# Generated by Django 3.1.14 on 2025-04-06 09:52

from django.db import migrations

def fill_empty_descriptions(apps, schema_editor):
    Pokemon = apps.get_model('pokemon_entities', 'Pokemon')
    Pokemon.objects.filter(description__isnull=True).update(description='')

class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0016_auto_20250403_1355'),
    ]

    operations = [
        migrations.RunPython(fill_empty_descriptions),
    ]
